### ISSUE TITLE
List caribdis as CAR tool 

### ISSUE THREAD

**Issue by davidgasquez** [filecoin-project/data-prep-tools#15]
Hector worked on https://github.com/hsanjuan/caribdis a while back! Thought it might be a great fit for the CAR Splitters/Joiners tool list.

**Comment by anjor** [comment]
Oh yeah this looks awesome. Would you like to file a PR @davidgasquez ?

**Comment by davidgasquez** [comment]
Sure! https://github.com/filecoin-project/data-prep-tools/pull/16.
